### ISSUE TITLE
Error submitting the form

### ISSUE THREAD

**Issue by Malik-Abdulaziz-Akbar** [trycourier/react-in-app-example#2]
Steps to reproduce:

- npm i
- provide AUTH_TOKEN in submit_form
- npm start

Getting error
<img width="1676" alt="Screenshot 2022-07-25 at 12 27 27 PM" src="https://user-images.githubusercontent.com/37701187/180721665-bf5f635f-0a7d-4927-8304-51cb0f3008e4.png">

**Comment by bwebs** [comment]
Closed with #6
